print("Welcome to the Band Name Generator")
city = input("What's the name of the city you grew up in?")
print(city)
petName = input("What's your pet's name?") 
print(petName)
print("Your band name could be " + city + " " + petName)